apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  ai:
    provider:
      openai:
        model: {{ .Values.backend.model | quote }}
      host: {{ .Values.api.host }}
      port: {{ .Values.api.port }}
      path: {{ .Values.api.path }}
  policies:
    auth:
      secretRef:
        name: {{ .Values.secret.name }}
    tls:
      sni: {{ .Values.api.sni }}
