apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.route.name }}
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.route.gateway.name }}
      namespace: {{ .Values.route.gateway.namespace }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.route.path }}
    filters:
      - type: URLRewrite
        urlRewrite:
          hostname: {{ .Values.api.host }}
    backendRefs:
    - name: {{ .Values.backend.name }}
      namespace: {{ .Values.namespace }}
      group: agentgateway.dev
      kind: AgentgatewayBackend
