apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace }}
spec:
  destination:
    namespace: {{ .Values.destination.namespace }}
    server: {{ .Values.destination.server }}
  project: {{ .Values.project }}
  source:
    chart: {{ .Values.source.chart }}
    helm:
      skipCrds: {{ .Values.source.helm.skipCrds }}
    repoURL: {{ .Values.source.repoURL }}
    targetRevision: {{ .Values.source.targetRevision }}
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.syncPolicy.automated.selfHeal }}
    syncOptions:
{{- range .Values.syncPolicy.syncOptions }}
    - {{ . }}
{{- end }}
{{- if .Values.syncPolicy.serverSideApply }}
    - ServerSideApply=true
{{- end }}
