{{- if and .Values.keycloak.enabled .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  namespace: {{ .Values.keycloak.namespace }}
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username }}
  password: {{ .Values.postgresql.auth.password }}
  database: {{ .Values.postgresql.auth.database }}
{{- end }}
