{{- if .Values.llm.cloudru.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.llm.cloudru.route.name }}
  namespace: {{ .Values.llm.cloudru.route.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.llm.cloudru.route.gateway.name }}
      namespace: {{ .Values.llm.cloudru.route.gateway.namespace }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.llm.cloudru.route.path | quote }}
    filters:
      - type: URLRewrite
        urlRewrite:
          hostname: {{ .Values.llm.cloudru.backend.host }}
    backendRefs:
    - name: {{ .Values.llm.cloudru.backend.name }}
      namespace: {{ .Values.llm.cloudru.backend.namespace }}
      group: agentgateway.dev
      kind: AgentgatewayBackend
{{- end }}