apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
{{- range .Values.listeners }}
  - protocol: {{ .protocol }}
    port: {{ .port }}
    name: {{ .name }}
    allowedRoutes:
      namespaces:
        from: {{ .allowedRoutes.namespaces.from }}
{{- end }}
