apiVersion: v2
name: agentgateway-llm
description: LLM providers for agentgateway
type: application
version: 0.1.0
dependencies:
  - name: agentgateway-library
    version: "0.1.0"
    repository: "file://../agentgateway-library"
