{{- if .Values.httpbin.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.httpbin.name }}
  namespace: {{ .Values.httpbin.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.httpbin.route.gateway.name }}
      namespace: {{ .Values.httpbin.route.gateway.namespace }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.httpbin.route.path | quote }}
      backendRefs:
        - name: {{ .Values.httpbin.name }}
          port: {{ .Values.httpbin.service.port }}
{{- end }}
